extends:
  - airbnb-base
  - plugin:prettier/recommended

overrides:
  - files:
      - '*.test.js'
    rules:
      global-require: 0
      no-new: 0
  - files:
      - '**/__mocks__/*.js'
    rules:
      class-methods-use-this: 0
      no-empty-function: 0

env:
  browser: true
  node: true
  jest: true
