name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm
        run: npm ci
      - name: 'lint configs'
        run: npx prettier -c 'data/*.yml' 'data/*.yaml'
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
